# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "gjp+4cxijmXhfpHaRv238Vk2MsW011AsbJodvkv6Bqh6K8fLt5+/IyFbZu35m+cAGif21M+/uNALdJNwIJyd6Yxd7dzUugzLRR9fH2w4BrqgeCldcIVkTRV/tWew92fa0hUNXiU+TKecjn4bGNyJq2zZl8BFW0jPiGHo04kHdrI9ofnqXabApAoSsvQjfMiKhV5v07kaM5klb+KelDjXFmuDO9MuxGdj8WwE44htG6anMc6VgQvdiS/mKKSh4OWz30UDY752fIoBAvec+irJg1hpzmUlLmIco21YL0IGsCxqrpKrdFXm6LK5VuissLRve+hyRZcuNgdbV/gKO3AhJ0dt1ea2a/c5wkcF5J1VkY6WUJVWEhctwOIXXzIvcqy9+tsc2Vol8ib9eI1fOXdTx3cjjVEq3LSYu9cdK6ztWzabrsyZTUbaoQREzNaLikDlJ6QVmIzaKshH5dRv31xbW1JUtFMi9RpMhlIZY+8aiNJZ4qa7ug5/6rM1+Qzk/FuPcO78v6aY2vZpQlTqJouA1YNmQF1cmJNPBqlrampAukZaR/XtBD4kxTNT7V4Hi5QcHJLkDxmMzHExZ2KqAw6oPq7tuNm41ol5tTpFySRijHou+kFzuV5e2p+tJnbtXXVh74WrxV2pj7LH52dzEO9PGPAuH8urOsc7/XVVvjxsROU="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
