travis:
  secure:
    BINSTAR_TOKEN: gjp+4cxijmXhfpHaRv238Vk2MsW011AsbJodvkv6Bqh6K8fLt5+/IyFbZu35m+cAGif21M+/uNALdJNwIJyd6Yxd7dzUugzLRR9fH2w4BrqgeCldcIVkTRV/tWew92fa0hUNXiU+TKecjn4bGNyJq2zZl8BFW0jPiGHo04kHdrI9ofnqXabApAoSsvQjfMiKhV5v07kaM5klb+KelDjXFmuDO9MuxGdj8WwE44htG6anMc6VgQvdiS/mKKSh4OWz30UDY752fIoBAvec+irJg1hpzmUlLmIco21YL0IGsCxqrpKrdFXm6LK5VuissLRve+hyRZcuNgdbV/gKO3AhJ0dt1ea2a/c5wkcF5J1VkY6WUJVWEhctwOIXXzIvcqy9+tsc2Vol8ib9eI1fOXdTx3cjjVEq3LSYu9cdK6ztWzabrsyZTUbaoQREzNaLikDlJ6QVmIzaKshH5dRv31xbW1JUtFMi9RpMhlIZY+8aiNJZ4qa7ug5/6rM1+Qzk/FuPcO78v6aY2vZpQlTqJouA1YNmQF1cmJNPBqlrampAukZaR/XtBD4kxTNT7V4Hi5QcHJLkDxmMzHExZ2KqAw6oPq7tuNm41ol5tTpFySRijHou+kFzuV5e2p+tJnbtXXVh74WrxV2pj7LH52dzEO9PGPAuH8urOsc7/XVVvjxsROU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
