travis:
  secure:
    BINSTAR_TOKEN: FOuWAWTXOZuvjJqWkUdVtk6YP1SWDeZ0/omm3bAD/1LAd2F3EOsVoOK6gnp2S7VbuAAPNUn+qg6joVcudNT2wJKLmYvjk3F3Y0OOc6C5UiQtPnITD+8G4bnvrf8kvhhDJYK/wIcT4ik3MB1DXAaWWLuBINZTLpMU/Kq4fuEFKTDtSL2pYIe3z5XIyJy0vv/oOqlJwQDfUcBfKprHZpYbtYzjBjozwVHp3N19lApShSVLZkrj2acRH1qutH0Qm2wsz50Jc+0IdiVEbtpIvjvXtpQSaV6LNndL7ve39RstX2gZknIH4iXgip/Zpzsj5Lr+ngCM8Kq8czdIm4eXTZp6ZUS0UkuHINITyQf9xRuLag0kM0QRmgSj2wlP00h5epaef4DZ0C8N3LGBzzo6fa96HQ8g8v5aWWxOdjGcQZvAq85lF/Y6ocQGGi74KmjTTOlWgJplGgpzXJhLhdyN3HJJsZwrkVJvMNtxNTd5SDqclIpmFU0sMXb6wbidLCyvMxR8qUb8V28z7LHOmzAb/xAHSs4uFOZPKGw1uXBBB9IpE2DGykFxLDkmUpS5mKeXZ6Qry6nnyxFnKXfCJkUu9OsEISeMjvMC3+8yV2Rhl1jXFXCWt+2NleEJJc4eJD31BbvnBRh0fLbk2C0rvc4AM+3LiuhZEjOGvQplDq7ogJbf6bc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
